export const EdgeFields = {
  weight: {
    label: "weight",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CRE(-ROB,-RUB)(R)": {
    label: "CRE(-ROB,-RUB)(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CRE(-RUB)(L)": {
    label: "CRE(-RUB)(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CRE(L)": {
    label: "CRE(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CRE(R)": {
    label: "CRE(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  INP: {
    label: "INP",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "MB(+ACA)(R)": {
    label: "MB(+ACA)(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "MB(L)": {
    label: "MB(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "MB(R)": {
    label: "MB(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SIP(L)": {
    label: "SIP(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SMP(L)": {
    label: "SMP(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SNP(L)": {
    label: "SNP(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b'2(R)": {
    label: "b'2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b'L(L)": {
    label: "b'L(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b'L(R)": {
    label: "b'L(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  cropped: {
    label: "cropped",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CA(R)": {
    label: "CA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PED(R)": {
    label: "PED(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a'1(R)": {
    label: "a'1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a'2(R)": {
    label: "a'2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a'3(R)": {
    label: "a'3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a'L(R)": {
    label: "a'L(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b'1(R)": {
    label: "b'1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "g2(R)": {
    label: "g2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "g4(R)": {
    label: "g4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "g5(R)": {
    label: "g5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "gL(R)": {
    label: "gL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SLP(R)": {
    label: "SLP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SNP(R)": {
    label: "SNP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "g1(R)": {
    label: "g1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SCL(R)": {
    label: "SCL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a3(R)": {
    label: "a3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "aL(R)": {
    label: "aL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SIP(R)": {
    label: "SIP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "mALT(R)": {
    label: "mALT(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "dACA(R)": {
    label: "dACA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "lACA(R)": {
    label: "lACA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SMP(R)": {
    label: "SMP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "bL(L)": {
    label: "bL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "gL(L)": {
    label: "gL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AVLP(R)": {
    label: "AVLP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ICL(R)": {
    label: "ICL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LAL(-GA)(R)": {
    label: "LAL(-GA)(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LAL(R)": {
    label: "LAL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LX(R)": {
    label: "LX(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "VLNP(R)": {
    label: "VLNP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a1(R)": {
    label: "a1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a2(R)": {
    label: "a2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b1(R)": {
    label: "b1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "b2(R)": {
    label: "b2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "bL(R)": {
    label: "bL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "g3(R)": {
    label: "g3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ATL(R)": {
    label: "ATL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CAN(R)": {
    label: "CAN(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "GOR(R)": {
    label: "GOR(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  IB: {
    label: "IB",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LH(R)": {
    label: "LH(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  PENP: {
    label: "PENP",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PLP(R)": {
    label: "PLP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PVLP(R)": {
    label: "PVLP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SPS(L)": {
    label: "SPS(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SPS(R)": {
    label: "SPS(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "VES(L)": {
    label: "VES(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "VES(R)": {
    label: "VES(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  VMNP: {
    label: "VMNP",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "vACA(R)": {
    label: "vACA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL(R)": {
    label: "AL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP1d(R)": {
    label: "AL-VP1d(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP1l(R)": {
    label: "AL-VP1l(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP1m(R)": {
    label: "AL-VP1m(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP2(R)": {
    label: "AL-VP2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP3(R)": {
    label: "AL-VP3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP4(R)": {
    label: "AL-VP4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VP5(R)": {
    label: "AL-VP5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  GNG: {
    label: "GNG",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  SAD: {
    label: "SAD",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SAD(-AMMC)": {
    label: "SAD(-AMMC)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "FLA(R)": {
    label: "FLA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ROB(R)": {
    label: "ROB(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "RUB(R)": {
    label: "RUB(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "a'L(L)": {
    label: "a'L(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "aL(L)": {
    label: "aL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LAL(L)": {
    label: "LAL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LX(L)": {
    label: "LX(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-D(R)": {
    label: "AL-D(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA1(R)": {
    label: "AL-DA1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC1(R)": {
    label: "AL-DC1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC2(R)": {
    label: "AL-DC2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC3(R)": {
    label: "AL-DC3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC4(R)": {
    label: "AL-DC4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL1(R)": {
    label: "AL-DL1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL2d(R)": {
    label: "AL-DL2d(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL2v(R)": {
    label: "AL-DL2v(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL3(R)": {
    label: "AL-DL3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL5(R)": {
    label: "AL-DL5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM4(R)": {
    label: "AL-DM4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM6(R)": {
    label: "AL-DM6(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DP1l(R)": {
    label: "AL-DP1l(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DP1m(R)": {
    label: "AL-DP1m(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-V(R)": {
    label: "AL-V(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA1d(R)": {
    label: "AL-VA1d(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA1v(R)": {
    label: "AL-VA1v(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA3(R)": {
    label: "AL-VA3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA4(R)": {
    label: "AL-VA4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA5(R)": {
    label: "AL-VA5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA6(R)": {
    label: "AL-VA6(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA7l(R)": {
    label: "AL-VA7l(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA7m(R)": {
    label: "AL-VA7m(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC1(R)": {
    label: "AL-VC1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC2(R)": {
    label: "AL-VC2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC3l(R)": {
    label: "AL-VC3l(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC5(R)": {
    label: "AL-VC5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VL1(R)": {
    label: "AL-VL1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VL2a(R)": {
    label: "AL-VL2a(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VL2p(R)": {
    label: "AL-VL2p(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM7v(R)": {
    label: "AL-VM7v(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AOTU(R)": {
    label: "AOTU(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "RUB(L)": {
    label: "RUB(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM1(R)": {
    label: "AL-VM1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM4(R)": {
    label: "AL-VM4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "EPA(R)": {
    label: "EPA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AME(R)": {
    label: "AME(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "OL(R)": {
    label: "OL(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ATL(L)": {
    label: "ATL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "BU(L)": {
    label: "BU(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "BU(R)": {
    label: "BU(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  CX: {
    label: "CX",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FB: {
    label: "FB",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "FB-column3": {
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl2: {
    label: "FBl2",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl3: {
    label: "FBl3",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl4: {
    label: "FBl4",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl5: {
    label: "FBl5",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl6: {
    label: "FBl6",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl7: {
    label: "FBl7",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ICL(L)": {
    label: "ICL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  NO: {
    label: "NO",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO(L)": {
    label: "NO(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO(R)": {
    label: "NO(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO1(L)": {
    label: "NO1(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO1(R)": {
    label: "NO1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO2(L)": {
    label: "NO2(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO2(R)": {
    label: "NO2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO3(L)": {
    label: "NO3(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "NO3(R)": {
    label: "NO3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  PB: {
    label: "PB",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R3)": {
    label: "PB(R3)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "mALT(L)": {
    label: "mALT(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "IPS(R)": {
    label: "IPS(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "WED(R)": {
    label: "WED(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "ME(R)": {
    label: "ME(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  POC: {
    label: "POC",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  AMMC: {
    label: "AMMC",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R8)": {
    label: "PB(R8)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "SCL(L)": {
    label: "SCL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  GC: {
    label: "GC",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LO(R)": {
    label: "LO(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "GA(R)": {
    label: "GA(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "LOP(R)": {
    label: "LOP(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM7d(R)": {
    label: "AL-VM7d(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA2(R)": {
    label: "AL-DA2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "GOR(L)": {
    label: "GOR(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "EPA(L)": {
    label: "EPA(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AOT(R)": {
    label: "AOT(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EB: {
    label: "EB",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr2r4: {
    label: "EBr2r4",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr3am: {
    label: "EBr3am",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr3d: {
    label: "EBr3d",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr3pw: {
    label: "EBr3pw",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr5: {
    label: "EBr5",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr6: {
    label: "EBr6",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl8: {
    label: "FBl8",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL(L)": {
    label: "AL(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L3)": {
    label: "PB(L3)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC4(L)": {
    label: "AL-DC4(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM1(L)": {
    label: "AL-DM1(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM2(L)": {
    label: "AL-DM2(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM3(L)": {
    label: "AL-DM3(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM4(L)": {
    label: "AL-DM4(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DP1m(L)": {
    label: "AL-DP1m(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM7d(L)": {
    label: "AL-VM7d(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM7v(L)": {
    label: "AL-VM7v(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-D(L)": {
    label: "AL-D(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA2(L)": {
    label: "AL-DA2(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC1(L)": {
    label: "AL-DC1(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DC2(L)": {
    label: "AL-DC2(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL5(L)": {
    label: "AL-DL5(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM6(L)": {
    label: "AL-DM6(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA6(L)": {
    label: "AL-VA6(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM5(L)": {
    label: "AL-DM5(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "CA(L)": {
    label: "CA(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L1)": {
    label: "PB(L1)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L2)": {
    label: "PB(L2)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L4)": {
    label: "PB(L4)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L5)": {
    label: "PB(L5)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L6)": {
    label: "PB(L6)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L7)": {
    label: "PB(L7)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L8)": {
    label: "PB(L8)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R1)": {
    label: "PB(R1)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R2)": {
    label: "PB(R2)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM1(R)": {
    label: "AL-DM1(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM3(R)": {
    label: "AL-DM3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA3(L)": {
    label: "AL-DA3(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA4m(L)": {
    label: "AL-DA4m(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VA2(R)": {
    label: "AL-VA2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC4(R)": {
    label: "AL-VC4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM3(R)": {
    label: "AL-VM3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM5d(R)": {
    label: "AL-VM5d(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM5v(R)": {
    label: "AL-VM5v(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM2(R)": {
    label: "AL-DM2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DM5(R)": {
    label: "AL-DM5(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA4m(R)": {
    label: "AL-DA4m(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VC3m(R)": {
    label: "AL-VC3m(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-VM2(R)": {
    label: "AL-VM2(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL4(L)": {
    label: "AL-DL4(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DL4(R)": {
    label: "AL-DL4(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl1: {
    label: "FBl1",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R4)": {
    label: "PB(R4)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R5)": {
    label: "PB(R5)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R6)": {
    label: "PB(R6)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R7)": {
    label: "PB(R7)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  FBl9: {
    label: "FBl9",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "GF(R)": {
    label: "GF(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  EBr1: {
    label: "EBr1",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(L9)": {
    label: "PB(L9)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AB(R)": {
    label: "AB(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AB(L)": {
    label: "AB(L)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "PB(R9)": {
    label: "PB(R9)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  PRW: {
    label: "PRW",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA3(R)": {
    label: "AL-DA3(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
  "AL-DA4l(R)": {
    label: "AL-DA4l(R)",
    type: "number",
    operators: ["greater", "less", "equal"],
    valueSources: ["value"],
  },
};
